# Generated by Django 4.2.1 on 2023-05-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_base', '0003_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='date_added',
        ),
    ]
