# Generated by Django 4.2.1 on 2023-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_base', '0004_remove_place_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
