name: Code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - name: Install python
       uses: actions/setup-python@v2
       with:
          python-version: 3.10
     - name: Install deps
        run:|
          python -m pip install --upgrade pip
          pip install requirments.txt
     - name: Run flake8
       run: flake8

     - name: Deploy 🚀
       uses: asemenyk24/github-pages-deploy-action@3.7.1
       with:
          GITHUB_TOKEN: ${{ secrets.KEY }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
